### ISSUE TITLE
.admin? method not defined for User class

### ISSUE THREAD

**Issue by brandon-a-hay** [spree-contrib/spree_drop_ship#58]
Hi,

I had a problem adding a new Spree supplier that it didn't recognize the admin? method

```ruby
<% if spree_current_user.admin? %>
```
I'm not sure why I don't have that method but I think it's because I am not using the spree_auth_devise gem. You could create a helper method to solve this easily:

```ruby
def admin?
  has_spree_role?("admin")
end
```

Putting that in a helper file should solve this. I would think it would also help for anyone coming from a different authentication system, as it references the Spree user class that a dev would have set up in the Spree initializer file.

Let me know what you think,

- Brandon

**Comment by JDutil** [comment]
Are you sure spree_curren_user wasn't just nil, and nil didn't know the admin? method.

**Comment by brandon-a-hay** [comment]
I believe so, because I called spree_current_user.has_spree_role?("admin")
which solved the issue and returned true for my admin user. You are using
the spree_auth_devise gem, correct?

**Comment by JDutil** [comment]
yea I was.  if you can solve the problem just changing to using has_spree_role? I'd just do that rather than creating an admin? method.

**Comment by brandon-a-hay** [comment]
I suppose that would work. I wasn't sure how many places in the code
referenced that admin? method so I just created it once to save time.
