### ISSUE TITLE
Getting a Variant duplication error when adding a new product with supplier

### ISSUE THREAD

**Issue by brandon-a-hay** [spree-contrib/spree_drop_ship#60]
Hi,

I'm getting an error from the latest commit (which scopes new products to a supplier). The error occurs when I create a new product:

"Validation failed: Variant has already been taken."

The product is created but the add_product_to_supplier method fails. The source of the problem was the @product.add_supplier!(try_spree_current_user.supplier_id) line, in the user decorator:

```ruby
def add_product_to_supplier
    if try_spree_current_user && try_spree_current_user.supplier?
      @product.add_supplier!(try_spree_current_user.supplier_id)
    end
  end
```

Is the new supplier association being treated like a product's variant? If so, maybe the solution is to adjust a validation method on the product (or variant?) model? I took a look at that code in spree_core (product.rb and variant.rb), but none of those validations seemed to be the culprit.

Curiously, I am also able to call the add_product_to_supplier method in the console on that same product and get it to have the supplier id no problem.

Anyone have ideas on this?

**Comment by ostraperlera** [comment]
Hi, @brandon-a-hay, 

Do you also have spree_marketplace installed? The culprit seems to be a collission between this method and spree_marketplace's Product#set_supplier method. 

I've created a PR with the fix I used myself here: JDutil/spree_marketplace#13

Good luck!

**Comment by brandon-a-hay** [comment]
Awesome! Thanks Maria I will look at that later.
