### ISSUE TITLE
spree 3.0 support

### ISSUE THREAD

**Issue by nykolaslima** [spree-contrib/spree_drop_ship#65]
Does master branch support spree 3.0?

**Comment by JDutil** [comment]
Checking gemspec for compatibility would indicate no:
https://github.com/spree-contrib/spree_drop_ship/blob/master/spree_drop_ship.gemspec#L22

**Comment by nykolaslima** [comment]
@JDutil do you have any expectation in supporting spree 3.0?

Thank you for your answer.

**Comment by JDutil** [comment]
I've stopped maintaining this project as I shutdown the site I wrote it for. There is already work done on supporting [2.4.x](https://github.com/spree-contrib/spree_drop_ship/pull/59) and [3.0.x](https://github.com/spree-contrib/spree_drop_ship/pull/63), but no one has finished making the specs pass for me to merge. If you'd like to take up where they left off that would be great, but I won't be spending time on it personally.

**Comment by JDutil** [comment]
There is now a 3-0-stable branch, and master now targets spree master.
