### ISSUE TITLE
When supplier tries to add new product I get Authorization Failure

### ISSUE THREAD

**Issue by patrickcorrigan** [spree-contrib/spree_drop_ship#70]

**Comment by JDutil** [comment]
They aren't authorized too: https://github.com/spree-contrib/spree_drop_ship/blob/master/app/models/spree/supplier_ability.rb#L12-L15 use spree_marketplace for that or change the ability to suit your needs.

**Comment by patrickcorrigan** [comment]
Fantastic. Thank you so much. My suppliers can now add products. Any idea why they can't see them after creation? The administrator can.

**Comment by lmahendra** [comment]
Hi @JDutil , @patrickcorrigan I am also getting same authorization error while adding products, however I have spree_marketplace installed as well, not able to get what's causing this, please help.
